- riderId: cmltg8c6h00js3vzd075d507u
  riderName: pogačar tadej
  scoritoName: T. Pogačar
  amountEUR: 7000000
  source: scorito-2026
- riderId: cmltg82zw000l3vzdq9a5t0fm
  riderName: philipsen jasper
  scoritoName: J. Philipsen
  amountEUR: 5000000
  source: scorito-2026
- riderId: cmltg8igq00ur3vzd0pcaczv7
  riderName: pedersen mads
  scoritoName: M. Pedersen
  amountEUR: 4500000
  source: scorito-2026
- riderId: cmltg85rx008r3vzd6feh2jcs
  riderName: van aert wout
  scoritoName: W. van Aert
  amountEUR: 4500000
  source: scorito-2026
- riderId: cmltg8gfw00ru3vzdas0b2li6
  riderName: milan jonathan
  scoritoName: J. Milan
  amountEUR: 3500000
  source: scorito-2026
- riderId: cmltg86kv00b03vzdo5iaed1o
  riderName: pidcock thomas
  scoritoName: T. Pidcock
  amountEUR: 3000000
  source: scorito-2026
- riderId: cmltg85tw008x3vzdjo6385sz
  riderName: brennan matthew
  scoritoName: M. Brennan
  amountEUR: 3000000
  source: scorito-2026
- riderId: cmltg85y8009c3vzdija1zfsu
  riderName: wellens tim
  scoritoName: T. Wellens
  amountEUR: 2500000
  source: scorito-2026
- riderId: cmltg8qht017c3vzdksyxsx4f
  riderName: evenepoel remco
  scoritoName: R. Evenepoel
  amountEUR: 2500000
  source: scorito-2026
- riderId: cmltg8ioq00vm3vzd89hl228z
  riderName: merlier tim
  scoritoName: T. Merlier
  amountEUR: 2500000
  source: scorito-2026
- riderId: cmltg8ctp00lq3vzdwfb64zhr
  riderName: jorgenson matteo
  scoritoName: M. Jorgenson
  amountEUR: 2500000
  source: scorito-2026
- riderId: cmltg85wm00963vzdwrr4hk3q
  riderName: laporte christophe
  scoritoName: C. Laporte
  amountEUR: 2500000
  source: scorito-2026
- riderId: cmltg84h2004o3vzdeaknavi2
  riderName: de lie arnaud
  scoritoName: A. De Lie
  amountEUR: 2500000
  source: scorito-2026
- riderId: cmltg8cfn00kf3vzdvqz4s0hy
  riderName: healy ben
  scoritoName: B. Healy
  amountEUR: 2000000
  source: scorito-2026
- riderId: cmltg8h4e00u43vzdpitkhxzf
  riderName: ganna filippo
  scoritoName: F. Ganna
  amountEUR: 2000000
  source: scorito-2026
- riderId: cmltg857700733vzdbl6c36nl
  riderName: magnier paul
  scoritoName: P. Magnier
  amountEUR: 2000000
  source: scorito-2026
- riderId: cmltg8cec00kc3vzdanwweoye
  riderName: powless neilson
  scoritoName: N. Powless
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg8639009r3vzdou8o4sz9
  riderName: vermeersch florian
  scoritoName: F. Vermeersch
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg859u007c3vzdefzklpjq
  riderName: stuyven jasper
  scoritoName: J. Stuyven
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg8iy300wq3vzdxko73u21
  riderName: matthews michael
  scoritoName: M. Matthews
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg878a00c63vzd4botaa83
  riderName: kung stefan
  scoritoName: S. Kung
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg830w000o3vzduudj91yp
  riderName: groves kaden
  scoritoName: K. Groves
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg84w6005u3vzdr4dpmsxa
  riderName: girmay biniam
  scoritoName: B. Girmay
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg8cpj00l83vzdg1wq2art
  riderName: gregoire romain
  scoritoName: R. Grégoire
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg8e5j00nn3vzdrjw3detd
  riderName: skjelmose mattias
  scoritoName: M. Skjelmose
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg84e4004i3vzdnac2nsuj
  riderName: vacek mathias
  scoritoName: M. Vacek
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg85zw009i3vzd3w8hclfe
  riderName: bjerg mikkel
  scoritoName: M. Bjerg
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg8ab300hr3vzdprdkw2ex
  riderName: groenewegen dylan
  scoritoName: D. Groenewegen
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg8629009o3vzdmqjc0z76
  riderName: politt nils
  scoritoName: N. Politt
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmluv6nl600iuxxvkbvjjrmka
  riderName: christen fabio
  scoritoName: J. Christen
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg8e4w00nk3vzd7u1jnabd
  riderName: ayuso juan
  scoritoName: J. Ayuso
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg8qti018g3vzdkgeokit5
  riderName: cosnefroy benoît
  scoritoName: B. Cosnefroy
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg838u00193vzdl717t91d
  riderName: mohorič matej
  scoritoName: M. Mohorič
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg8qdj016s3vzd6zqhe76l
  riderName: nys thibau
  scoritoName: T. Nys
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg849m00463vzdxu4x6v2u
  riderName: skujiņš toms
  scoritoName: T. Skujiņš
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg86bi00ac3vzdlsnccuoj
  riderName: teunissen mike
  scoritoName: M. Teunissen
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg8kp900yr3vzdce25qgv4
  riderName: morgado antonio
  scoritoName: A. Morgado
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg87fv00co3vzdzmt84sq6
  riderName: trentin matteo
  scoritoName: M. Trentin
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg8c7y00jx3vzdsruwdhuv
  riderName: novak domen
  scoritoName: D. Novak
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg8a9600ho3vzdzsi3avce
  riderName: fretin milan
  scoritoName: M. Fretin
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg89n700fj3vzdg9inp2u1
  riderName: bittner pavel
  scoritoName: P. Bittner
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg8elp00p03vzdx2ylfz9z
  riderName: vauquelin kevin
  scoritoName: K. Vauquelin
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg851h006f3vzdm8itsx35
  riderName: meeus jordi
  scoritoName: J. Meeus
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg8e8h00ny3vzdu4dtgo05
  riderName: sivakov pavel
  scoritoName: P. Sivakov
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg860s009l3vzdrmay9ttv
  riderName: herregodts rune
  scoritoName: R. Herregodts
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg8e7j00nv3vzdnpj6lhxk
  riderName: almeida joão
  scoritoName: J. Almeida
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg8e6r00ns3vzdwag1qk92
  riderName: arrieta igor
  scoritoName: I. Arrieta
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg8e3u00nf3vzdngv3d2wd
  riderName: oliveira nelson
  scoritoName: I. Oliveira
  amountEUR: 500000
  source: scorito-2026
- riderId: cmlskm2yr009i108u5g60sqdf
  riderName: oliveira rui
  scoritoName: R. Oliveira
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg8gc400rj3vzdsbunzki5
  riderName: andresen tobias lund
  scoritoName: T. Andresen
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg8557006u3vzdhtb96j2q
  riderName: van poppel danny
  scoritoName: D. van Poppel
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg8qik017f3vzdg1vkm9t2
  riderName: van gils maxim
  scoritoName: M. Van Gils
  amountEUR: 1000000
  source: scorito-2026- riderId: cmlskm1x4000r108uv9e9vtfb
  riderName: bayer tobias
  amountEUR: 750000
  source: scorito-2026
- riderId: cmlskm1xg000u108uif5qvjix
  riderName: belmans lennert
  amountEUR: 750000
  source: scorito-2026
- riderId: cmlskm1xr000x108uyqpkmzna
  riderName: geens jonas
  amountEUR: 750000
  source: scorito-2026
- riderId: cmlskm1y00010108uophqigei
  riderName: planckaert edward
  amountEUR: 750000
  source: scorito-2026
- riderId: cmlskm2b9004c108ukndfztcp
  riderName: söderqvist jakob
  amountEUR: 750000
  source: scorito-2026
- riderId: cmlskm2l9006o108ur0fp6253
  riderName: pithie laurence
  amountEUR: 750000
  source: scorito-2026
- riderId: cmlskm2mv0070108urjtz0g2i
  riderName: vermeersch gianni
  amountEUR: 750000
  source: scorito-2026
- riderId: cmlskm2ol007c108u682h0yx2
  riderName: rex laurenz
  amountEUR: 750000
  source: scorito-2026
- riderId: cmlskm2y4009c108u2xkq00t6
  riderName: zingle axel
  amountEUR: 750000
  source: scorito-2026
- riderId: cmlskm30c009x108uiricxwss
  riderName: ballerini davide
  amountEUR: 750000
  source: scorito-2026
- riderId: cmlskm35n00b0108uyyly5orj
  riderName: teuns dylan
  amountEUR: 750000
  source: scorito-2026
- riderId: cmlskm90o00ei108ubl9em0cf
  riderName: sentjens sente
  amountEUR: 750000
  source: scorito-2026
- riderId: cmlskm99h00gv108u9kz87y2m
  riderName: hofstetter hugo
  amountEUR: 750000
  source: scorito-2026
- riderId: cmlskmf5a00iq108u01shlxon
  riderName: lapeira paul
  amountEUR: 750000
  source: scorito-2026
- riderId: cmlskmfj400mc108udextrctp
  riderName: laurance axel
  amountEUR: 750000
  source: scorito-2026
- riderId: cmlskmfkh00ml108uzgqunlvj
  riderName: busatto francesco
  amountEUR: 750000
  source: scorito-2026
- riderId: cmlskml9i00og108umzntt44c
  riderName: martinez lenny
  amountEUR: 750000
  source: scorito-2026
- riderId: cmlskmlbt00oz108ukk39sf8l
  riderName: ballerstedt maurice
  amountEUR: 750000
  source: scorito-2026
- riderId: cmlskmlc600p2108uorefh38s
  riderName: dockx aaron
  amountEUR: 750000
  source: scorito-2026
- riderId: cmlskmldz00pe108ueonyhgu2
  riderName: onley oscar
  amountEUR: 750000
  source: scorito-2026
- riderId: cmlskpaa10137108urgci6x8b
  riderName: jakobsen fabio
  amountEUR: 750000
  source: scorito-2026
- riderId: cmlskqhut017a108uprr6wy6c
  riderName: ciccone giulio
  amountEUR: 750000
  source: scorito-2026
- riderId: cmlskm2bm004f108uw16ww3yt
  riderName: teutenberg tim torn
  amountEUR: 750000
  source: scorito-2026