- riderId: cmltg8c6h00js3vzd075d507u
  riderName: pogačar tadej
  scoritoName: T. Pogačar
  amountEUR: 7000000
  source: scorito-2026
- riderId: cmltg82zw000l3vzdq9a5t0fm
  riderName: philipsen jasper
  scoritoName: J. Philipsen
  amountEUR: 5000000
  source: scorito-2026
- riderId: cmltg8igq00ur3vzd0pcaczv7
  riderName: pedersen mads
  scoritoName: M. Pedersen
  amountEUR: 4500000
  source: scorito-2026
- riderId: cmltg85rx008r3vzd6feh2jcs
  riderName: van aert wout
  scoritoName: W. van Aert
  amountEUR: 4500000
  source: scorito-2026
- riderId: cmltg8gfw00ru3vzdas0b2li6
  riderName: milan jonathan
  scoritoName: J. Milan
  amountEUR: 3500000
  source: scorito-2026
- riderId: cmltg86kv00b03vzdo5iaed1o
  riderName: pidcock thomas
  scoritoName: T. Pidcock
  amountEUR: 3000000
  source: scorito-2026
- riderId: cmltg85tw008x3vzdjo6385sz
  riderName: brennan matthew
  scoritoName: M. Brennan
  amountEUR: 3000000
  source: scorito-2026
- riderId: cmltg85y8009c3vzdija1zfsu
  riderName: wellens tim
  scoritoName: T. Wellens
  amountEUR: 2500000
  source: scorito-2026
- riderId: cmltg8qht017c3vzdksyxsx4f
  riderName: evenepoel remco
  scoritoName: R. Evenepoel
  amountEUR: 2500000
  source: scorito-2026
- riderId: cmltg8ioq00vm3vzd89hl228z
  riderName: merlier tim
  scoritoName: T. Merlier
  amountEUR: 2500000
  source: scorito-2026
- riderId: cmltg8ctp00lq3vzdwfb64zhr
  riderName: jorgenson matteo
  scoritoName: M. Jorgenson
  amountEUR: 2500000
  source: scorito-2026
- riderId: cmltg85wm00963vzdwrr4hk3q
  riderName: laporte christophe
  scoritoName: C. Laporte
  amountEUR: 2500000
  source: scorito-2026
- riderId: cmltg84h2004o3vzdeaknavi2
  riderName: de lie arnaud
  scoritoName: A. De Lie
  amountEUR: 2500000
  source: scorito-2026
- riderId: cmltg8cfn00kf3vzdvqz4s0hy
  riderName: healy ben
  scoritoName: B. Healy
  amountEUR: 2000000
  source: scorito-2026
- riderId: cmltg8h4e00u43vzdpitkhxzf
  riderName: ganna filippo
  scoritoName: F. Ganna
  amountEUR: 2000000
  source: scorito-2026
- riderId: cmltg857700733vzdbl6c36nl
  riderName: magnier paul
  scoritoName: P. Magnier
  amountEUR: 2000000
  source: scorito-2026
- riderId: cmltg8cec00kc3vzdanwweoye
  riderName: powless neilson
  scoritoName: N. Powless
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg8639009r3vzdou8o4sz9
  riderName: vermeersch florian
  scoritoName: F. Vermeersch
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg859u007c3vzdefzklpjq
  riderName: stuyven jasper
  scoritoName: J. Stuyven
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg8iy300wq3vzdxko73u21
  riderName: matthews michael
  scoritoName: M. Matthews
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg878a00c63vzd4botaa83
  riderName: kung stefan
  scoritoName: S. Kung
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg830w000o3vzduudj91yp
  riderName: groves kaden
  scoritoName: K. Groves
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg84w6005u3vzdr4dpmsxa
  riderName: girmay biniam
  scoritoName: B. Girmay
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg8cpj00l83vzdg1wq2art
  riderName: gregoire romain
  scoritoName: R. Grégoire
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg8e5j00nn3vzdrjw3detd
  riderName: skjelmose mattias
  scoritoName: M. Skjelmose
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg84e4004i3vzdnac2nsuj
  riderName: vacek mathias
  scoritoName: M. Vacek
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg85zw009i3vzd3w8hclfe
  riderName: bjerg mikkel
  scoritoName: M. Bjerg
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg8ab300hr3vzdprdkw2ex
  riderName: groenewegen dylan
  scoritoName: D. Groenewegen
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg8629009o3vzdmqjc0z76
  riderName: politt nils
  scoritoName: N. Politt
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmluv6nl600iuxxvkbvjjrmka
  riderName: christen fabio
  scoritoName: J. Christen
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg8e4w00nk3vzd7u1jnabd
  riderName: ayuso juan
  scoritoName: J. Ayuso
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg8qti018g3vzdkgeokit5
  riderName: cosnefroy benoît
  scoritoName: B. Cosnefroy
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg838u00193vzdl717t91d
  riderName: mohorič matej
  scoritoName: M. Mohorič
  amountEUR: 1500000
  source: scorito-2026
- riderId: cmltg8qdj016s3vzd6zqhe76l
  riderName: nys thibau
  scoritoName: T. Nys
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg849m00463vzdxu4x6v2u
  riderName: skujiņš toms
  scoritoName: T. Skujiņš
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg86bi00ac3vzdlsnccuoj
  riderName: teunissen mike
  scoritoName: M. Teunissen
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg8kp900yr3vzdce25qgv4
  riderName: morgado antonio
  scoritoName: A. Morgado
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg87fv00co3vzdzmt84sq6
  riderName: trentin matteo
  scoritoName: M. Trentin
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg8c7y00jx3vzdsruwdhuv
  riderName: novak domen
  scoritoName: D. Novak
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg8a9600ho3vzdzsi3avce
  riderName: fretin milan
  scoritoName: M. Fretin
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg89n700fj3vzdg9inp2u1
  riderName: bittner pavel
  scoritoName: P. Bittner
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg8elp00p03vzdx2ylfz9z
  riderName: vauquelin kevin
  scoritoName: K. Vauquelin
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg851h006f3vzdm8itsx35
  riderName: meeus jordi
  scoritoName: J. Meeus
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg8e8h00ny3vzdu4dtgo05
  riderName: sivakov pavel
  scoritoName: P. Sivakov
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg860s009l3vzdrmay9ttv
  riderName: herregodts rune
  scoritoName: R. Herregodts
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg8e7j00nv3vzdnpj6lhxk
  riderName: almeida joão
  scoritoName: J. Almeida
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg8e6r00ns3vzdwag1qk92
  riderName: arrieta igor
  scoritoName: I. Arrieta
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg8e3u00nf3vzdngv3d2wd
  riderName: oliveira nelson
  scoritoName: I. Oliveira
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg8gc400rj3vzdsbunzki5
  riderName: andresen tobias lund
  scoritoName: T. Andresen
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg8e3u00nf3vzdngv3d2wd
  riderName: oliveira nelson
  scoritoName: R. Oliveira
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg8557006u3vzdhtb96j2q
  riderName: van poppel danny
  scoritoName: D. van Poppel
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmltg8qik017f3vzdg1vkm9t2
  riderName: van gils maxim
  scoritoName: M. Van Gils
  amountEUR: 1000000
  source: scorito-2026
- riderId: cmlskmliu00qn108u96r01d76
  riderName: rondel mathys
  scoritoName: M. Rondel
  amountEUR: 750000
  source: scorito-2026
- riderId: cmlskmf6200iz108u2eu0v863
  riderName: seixas paul
  scoritoName: P. Seixas
  amountEUR: 750000
  source: scorito-2026
- riderId: cmlskmrdu00t0108ugabnimqd
  riderName: storer michael
  scoritoName: M. Storer
  amountEUR: 750000
  source: scorito-2026
- riderId: cmlskmlhk00qb108uj1uemd2f
  riderName: tejada harold
  scoritoName: H. Tejada
  amountEUR: 750000
  source: scorito-2026
- riderId: cmlskmlam00op108u5aueulj9
  riderName: thomas benjamin
  scoritoName: B. Thomas
  amountEUR: 750000
  source: scorito-2026
- riderId: cmlskmrb000sd108ut9diviis
  riderName: tiberi antonio
  scoritoName: A. Tiberi
  amountEUR: 750000
  source: scorito-2026
- riderId: cmlskmf4b00ih108uvpeq6fb4
  riderName: widar jarno
  scoritoName: J. Widar
  amountEUR: 500000
  source: scorito-2026
- riderId: cmlskm2d5004u108ueg6parkn
  riderName: artz huub
  scoritoName: H. Artz
  amountEUR: 500000
  source: scorito-2026
- riderId: cmlskm2fd005f108u78ufqh0s
  riderName: aular orluis
  scoritoName: O. Aular
  amountEUR: 500000
  source: scorito-2026
- riderId: cmlskmfg000lg108uhh4e5jwa
  riderName: barguil warren
  scoritoName: W. Barguil
  amountEUR: 500000
  source: scorito-2026
- riderId: cmlskm2610033108uwz39gwpr
  riderName: barthe cyril
  scoritoName: C. Barthe
  amountEUR: 500000
  source: scorito-2026
- riderId: cmlskmrew00t9108u9ofi5lms
  riderName: berthet clement
  scoritoName: C. Berthet
  amountEUR: 500000
  source: scorito-2026
- riderId: cmlskm30o00a0108ufrhzcvmg
  riderName: bettiol alberto
  scoritoName: A. Bettiol
  amountEUR: 500000
  source: scorito-2026
- riderId: cmlskm34h00ao108u2z0x0vkz
  riderName: biermans jenthe
  scoritoName: J. Biermans
  amountEUR: 500000
  source: scorito-2026
- riderId: cmlskm3gn00e0108u5cjzswor
  riderName: bloem joren
  scoritoName: J. Bloem
  amountEUR: 500000
  source: scorito-2026
- riderId: cmlskm2pw007o108uootcho8s
  riderName: capiot amaury
  scoritoName: A. Capiot
  amountEUR: 500000
  source: scorito-2026
- riderId: cmlskmrbc00sg108ukh1cvquv
  riderName: carapaz richard
  scoritoName: R. Carapaz
  amountEUR: 500000
  source: scorito-2026
- riderId: cmlskm21y0020108uvxm4m3x2
  riderName: chamberlain oscar
  scoritoName: O. Chamberlain
  amountEUR: 500000
  source: scorito-2026
- riderId: cmlskml9w00oj108uu1kigbn2
  riderName: coquard bryan
  scoritoName: B. Coquard
  amountEUR: 500000
  source: scorito-2026
- riderId: cmlskm9er00i8108u10xxxzik
  riderName: crabbe tom
  scoritoName: T. Crabbe
  amountEUR: 500000
  source: scorito-2026
- riderId: cmlskm3cx00cu108uwm2tygv7
  riderName: deweirdt siebe
  scoritoName: S. Deweirdt
  amountEUR: 500000
  source: scorito-2026
- riderId: cmlskm22n0026108up5b693wo
  riderName: dewulf stan
  scoritoName: S. Dewulf
  amountEUR: 500000
  source: scorito-2026
- riderId: cmlskm2r1007x108u3ouzqurz
  riderName: donaldson robert
  scoritoName: R. Donaldson
  amountEUR: 500000
  source: scorito-2026
- riderId: cmlskm2kv006l108u74ak6ns8
  riderName: drizners jarrad
  scoritoName: J. Drizners
  amountEUR: 500000
  source: scorito-2026
- riderId: cmlskmfb400ka108utz1wu1uf
  riderName: eulalio afonso
  scoritoName: A. Eulalio
  amountEUR: 500000
  source: scorito-2026
- riderId: cmlskm2tk008f108ufi3suzwq
  riderName: flynn sean
  scoritoName: S. Flynn
  amountEUR: 500000
  source: scorito-2026
- riderId: cmlskm2rr0080108ulbsp6ues
  riderName: foldager anders
  scoritoName: A. Foldager
  amountEUR: 500000
  source: scorito-2026
