- name: Omloop Het Nieuwsblad
  slug: omloop-het-nieuwsblad
  date: 2026-02-28
  url: https://www.procyclingstats.com/race/omloop-het-nieuwsblad/2026/startlist
- name: Kuurne - Brussel - Kuurne
  slug: kuurne-brussel-kuurne
  date: 2026-03-01
  url: https://www.procyclingstats.com/race/kuurne-brussel-kuurne/2026/startlist
- name: Strade Bianche
  slug: strade-bianche
  date: 2026-03-07
  url: https://www.procyclingstats.com/race/strade-bianche/2026/startlist
- name: Parijs - Nice Etappe 7
  slug: paris-nice-etappe-7
  date: 2026-03-14
  url: https://www.procyclingstats.com/race/paris-nice/2026/startlist
- name: Tirreno-Adriatico Etappe 7
  slug: tirreno-adriatico-etappe-7
  date: 2026-03-15
  url: https://www.procyclingstats.com/race/tirreno-adriatico/2026/startlist
- name: Milaan - San Remo
  slug: milano-san-remo
  date: 2026-03-21
  url: https://www.procyclingstats.com/race/milano-san-remo/2026/startlist
- name: Brugge - De Panne
  slug: brugge-de-panne
  date: 2026-03-25
  url: https://www.procyclingstats.com/race/brugge-de-panne/2026/startlist
- name: E3 Saxo Classic
  slug: e3-saxo-classic
  date: 2026-03-27
  url: https://www.procyclingstats.com/race/e3-saxo-classic/2026/startlist
- name: Gent - Wevelgem
  slug: gent-wevelgem
  date: 2026-03-29
  url: https://www.procyclingstats.com/race/gent-wevelgem/2026/startlist
- name: Dwars door Vlaanderen
  slug: dwars-door-vlaanderen
  date: 2026-04-01
  url: https://www.procyclingstats.com/race/dwars-door-vlaanderen/2026/startlist
- name: Ronde van Vlaanderen
  slug: ronde-van-vlaanderen
  date: 2026-04-05
  url: https://www.procyclingstats.com/race/ronde-van-vlaanderen/2026/startlist
- name: Scheldeprijs
  slug: scheldeprijs
  date: 2026-04-08
  url: https://www.procyclingstats.com/race/scheldeprijs/2026/startlist
- name: Parijs - Roubaix
  slug: paris-roubaix
  date: 2026-04-12
  url: https://www.procyclingstats.com/race/paris-roubaix/2026/startlist
- name: Brabantse Pijl
  slug: brabantse-pijl
  date: 2026-04-17
  url: https://www.procyclingstats.com/race/brabantse-pijl/2026/startlist
- name: Amstel Gold Race
  slug: amstel-gold-race
  date: 2026-04-19
  url: https://www.procyclingstats.com/race/amstel-gold-race/2026/startlist
- name: Waalse Pijl
  slug: waalse-pijl
  date: 2026-04-22
  url: https://www.procyclingstats.com/race/waalse-pijl/2026/startlist
- name: Luik - Bastenaken - Luik
  slug: luik-bastenaken-luik
  date: 2026-04-26
  url: https://www.procyclingstats.com/race/liege-bastogne-liege/2026/startlist
